### PR TITLE
Issue/222

### LINKED ISSUE #222: EmeraldDateFilter returning last year when last seven days is selected
**Describe the bug**
EmeraldDateFilter returns last year when last seven days is selected on date 2020-12-29

**To Reproduce**
1. On the last week of 2020
2. select last seven days
3. check the selected date

**Expected behavior**
Select last seven days

### PR DESCRIPTION
**Pull request by renanrbs**
#### What this PR does?
fixes #222 

#### How should it be manually tested?
Select last seven days filter on the last week of 2020

### CODE REVIEW

**Review by danielefreitas — APPROVED** [review]

**Review by Luan-BK — APPROVED** [review]

**Review by VictorGTdaCruz — APPROVED** [review]

**Review by VictorGTdaCruz — APPROVED** [review]

File: emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/calendar/EmeraldDateFilter.kt [hunk 1]
```diff
@@ -129,20 +129,19 @@ class EmeraldDateFilter : ConstraintLayout {
...
+                endDate.year(), endDate.month(), endDate.day()).show()
         }
     }
 
     internal fun isValidDateRange(start: Calendar, end: Calendar): Boolean {
         val differenceBetweenDates = end.toStartOfDay().timeInMillis - start.toStartOfDay().timeInMillis
-        val amountOfDays = end.get(Calendar.DAY_OF_YEAR) - start.get(Calendar.DAY_OF_YEAR) + 1
-
+        val maxMillisRange = (maxDaysRange ?: 0) * MILLISECOND_MULTIPLIER
         when {
```
Comment (SamilaRuane) [inline emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/calendar/EmeraldDateFilter.kt:139]: @renanrbs o que acha de aqui usar o `TimeUnit.DAYS.toMillis()` ?

**Review by SamilaRuane — APPROVED** [review]

**Review by italomarcel — DISMISSED** [review]

**Review by SamilaRuane — APPROVED** [review]

**Review by adrielcafe — APPROVED** [review]

**Review by italomarcel — APPROVED** [review]
